# docker-compose.yml
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
  php:
    container_name: php
    build: ./docker/php
    links:
      - mysql
    ports:
      - "2000:2000"
    volumes:
      - ./src:/usr/local/apache2/htdocs
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /usr/local/apache2/htdocs
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_oc
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8086:80